_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True

  HEADS:
    POOL_LAYER: gempool

  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("SmallVeRiWild", "MediumVeRiWild", "LargeVeRiWild",)

SOLVER:
  IMS_PER_BATCH: 256
  MAX_EPOCH: 120
  STEPS: [30, 70, 90]
  BIAS_LR_FACTOR: 1.0
  ETA_MIN_LR: 0.0000003
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5000

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 20
  IMS_PER_BATCH: 64

OUTPUT_DIR: logs/veriwild/bagtricks_R50-ibn_4gpu
